# Tensorflow
tensor是张量的意思,顾名思义,是一个能够存储多维数组的tensorflow数据结构,它的元素可以是int类型,float类型,bool类型,还有string类型等等

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(32)
b = tf.constant(10)
c = tf.add(a,b)

sess = tf.Session()
print(sess.run(c))
sess.close()

42


在tensorflow下, 所有的tensor都是一种符号, 用来构建整个Graph的, 它是什么值并不重要, 所以就无法在构建图之后进行打印看它的值了

In [3]:
print(a)
print(b)
print(c)

Tensor("Const:0", shape=(), dtype=int32)
Tensor("Const_1:0", shape=(), dtype=int32)
Tensor("Add:0", shape=(), dtype=int32)


### 1.会话(Session)

In [4]:
sess = tf.Session()
print(sess.run(a))
print(sess.run([a, b]))
print(sess.run([a, b, c]))

32
[32, 10]
[32, 10, 42]


我们可以将执行图的结果保存到正常的变量中, tensorflow称这个过程为fetch. 

In [5]:
py_a = sess.run(a)
print(type(py_a))
print(py_a)

<class 'numpy.int32'>
32


### 2.Tensors
tensor可以有很多形式

In [6]:
hello = tf.constant('hello, tensorflow!')
boolean = tf.constant('true')
int_array = tf.constant([1,2],dtype=tf.int32)
float_array = tf.constant([3,4],dtype=tf.float32)

print(sess.run(hello))
print(sess.run(boolean))
print(sess.run(int_array))
print(sess.run(float_array))


b'hello, tensorflow!'
b'true'
[1 2]
[3. 4.]


tensor还可以有名字, 在定义每个tensor的时候添加参数name的值就可以.这是一个可选参数

In [7]:
my_name_is_hello = tf.constant('Hello', name='Hello')
my_name_is_world = tf.constant('World', name='World')
print('tensor {}: {}'.format(my_name_is_hello.name, sess.run(my_name_is_hello)))
print('tensor {}: {}'.format(my_name_is_world.name, sess.run(my_name_is_world)))

tensor Hello:0: b'Hello'
tensor World:0: b'World'


### 3.Operations
tensorflow原生支持很多的operation, 以后我们将用op来简称operation. 注意, op也可以有名字用来标识

In [8]:
d = tf.add_n([a,b,b])
e = tf.subtract(a,b)
f = tf.multiply(a,b)
g = tf.divide(a,b)
h = tf.mod(a,b)

print('a:{}'.format(sess.run(a)))
print('b:{}'.format(sess.run(b)))
print(sess.run(d))
print(sess.run(e))
print(sess.run(f))
print(sess.run(g))
print(sess.run(h))

a:32
b:10
52
22
320
3.2
2


类型转换以及其他运算

In [9]:
print(type(sess.run(a)))
a_float = tf.cast(a,dtype=tf.float32)
print(type(sess.run(a_float)))

<class 'numpy.int32'>
<class 'numpy.float32'>


In [10]:
i = tf.sin(a_float)
j = tf.exp(tf.divide(1.0, a_float))
k = tf.add(i, tf.log(i))

print(sess.run(i))
print(sess.run(j))
print(sess.run(k))


0.5514267
1.0317434
-0.043819606


#### 矩阵运算

In [11]:

mat_a = tf.constant([1,2,3,4])
mat_b = tf.constant([1,3,5,7,9,11])

mat_a = tf.reshape(mat_a, (2,2))
mat_b = tf.reshape(mat_b, (2,3))

print(sess.run(mat_a))
print(sess.run(mat_b))

[[1 2]
 [3 4]]
[[ 1  3  5]
 [ 7  9 11]]


In [12]:
vec_a = tf.constant([1,2])
mat_c = tf.matmul(mat_a,mat_b)
mat_d = tf.multiply(mat_a,vec_a)
print(sess.run(mat_c))
print(sess.run(mat_d))

[[15 21 27]
 [31 45 59]]
[[1 4]
 [3 8]]


#### numpy_like tensors
tensorflow采用了很多类似于numpy的数据定义方式

In [13]:
zeros = tf.zeros((2,3),dtype=tf.int32)
zeros_like = tf.zeros_like(ones)
ones = tf.ones((3,2),dtype=tf.int32)
ones_like = tf.ones_like(zeros)

print('{}\n{}\n'.format('zeros:',sess.run(zeros)))
print('{}\n{}\n'.format('ones:',sess.run(ones)))
print('{}\n{}\n'.format('zeros_like:',sess.run(zeros_like)))
print('{}\n{}\n'.format('ones_like:',sess.run(ones_like)))

NameError: name 'ones' is not defined

In [ ]:
fill = tf.fill((2,4),2)
linspace = tf.linspace(1.,5.,5)
ranger = tf.range(3,10,delta=3)

print('{}:\n{}\n'.format('fill', sess.run(fill)))
print('{}:\n{}\n'.format('linspace', sess.run(linspace)))
print('{}:\n{}\n'.format('range', sess.run(ranger)))

#### 关闭Session
session可以打开就需要被关闭, 用下面这行命令

In [ ]:
sess.close()