# 基本的数据结构

### 1.空值和变量
空值是python里面一个特殊的值，用None表示。None不能理解为0，因为0是有意义的。

### 2.整数
python可以处理任意大小的整数，包括负数，在程序中表现的方式和数学的写法一模一样，比如3或者-1等等。我们可以用type来显示一个数据的类型，比如我们可以打印出3的数据类型

In [2]:
type(3)

int

### 3.浮点型
所谓的浮点数，就是小数，比如，，等等。对于很大或者很小的浮点数，必须用科学计数法表示，把10用e替代，比如就是1.23e9或者12.3e8,而可以写成1.2e-2等等。

In [5]:
print(1.23e10,'\t',1.2e-2)

12300000000.0 	 0.012


### 4.字符型
字符型字符型字符串是以''或者""括起来的任意文本，比如如果字符串内部包含'或者"可以使用\来表示转义


In [8]:
s = 'abc'
print(s)
print(len(s))
print('I\'am \"ok\"')

abc
3
I'am "ok"


In [10]:
d = 'a:{},b:{}'.format(1,2)
print(d)

a:1,b:2


补充：
字符串其他使用方法

In [16]:
s = 'hello'
print(s.capitalize())
print(s.upper())
print(s.replace('e','a'))
print('   world   '.strip())

Hello
HELLO
hallo
world


### 5.布尔值
布尔值和布尔代数表示的含义完全相同，一个布尔值只有True和False两种值，要么是True，要么是False，在python中可以直接使用True和False来表示布尔值，注意大小写。

In [19]:
print(type(True))
print(3<2)

<class 'bool'>
False


同时布尔值可以用and、or和not运算，比如同时布尔值可以用and、or和not运算，比如

In [20]:
t = True
f = False
print(t and f)
print(t or f)
print(not t)
print(t != f)

False
True
False
True


# 容器
列表，字典，集合，元组

### 1.列表
列表是Python中非常常⻅的容器，可以看做一个序列，序列中的每个元素都可以修改，且可以是不同的数据类型，同时序列的⻓度也能够进行修改

In [37]:
xs = [3, 1, 2]    # 创建一个序列
print(xs, xs[2])  # 打印出 "[3, 1, 2]"和序列中的第3个元素
print(xs[-1])     # 打印出序列的最后一个元素
xs[2] = 'foo'     # 将序列中第三个元素进行重新赋值
print(xs)        
xs.append('bar')  # 在列表的最后加一个新元素
print(xs)
x = xs.pop()      # 移除列表的最后一个元素，同时将这个元素返回到一个变量中
print(x, xs)

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


### 切片
除了一次访问列表中的一个元素，Python还提供了一种更高效的使用方式叫做切片

In [36]:
nums = [0, 1, 2, 3, 4]
print(nums[2:4])   # 得到一个切片，下标从2到4，但是不包括4
print(nums[2:])    # 得到一个切片，下标从2到列表结束
print(nums[:2])    # 得到一个切片，下标从开始到2，不包括2
print(nums[:])     # 得到整个列表的元素
print(nums[:-1])   # 得到一个切片，下标从开始到最后一个元素，不包括最后一个元素
nums[2:4] = [8, 9] # 将列表中下标从2到4(不包括4)的切片替换成新的元素
print(nums)

[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


### 循环
你可以对列表中的元素进行循环，就是从列表的开始遍历到列表的结束

In [38]:
animals = ['cat', 'dog', 'monkey']
for i in animals:
    print(i)

cat
dog
monkey


如果想取得每个元素的下标，可以通过调用内置函数enumerate来实现。如果想取得每个元素的下标，可以通过调用内置函数enumerate来实现

In [39]:
animals = ['cat', 'dog', 'monkey']
for i,annimal in enumerate(animals):
    print(i,annimal)

0 cat
1 dog
2 monkey


### 补充

In [43]:
nums = [0,1,2,3,4]
result = [x+2 for x in nums]
print(result)

[2, 3, 4, 5, 6]


### 2.集合
集合里面的元素没有顺序关系，同时里面也没有重复的元素

In [46]:
animals = {'cat', 'dog'}
print('cat'in animals)    # 验证该元素是否在集合中
print('fish'in animals)
animals.add('fish')       # 在集合里面添加元素
print('fish'in animals)
print(len(animals))       # 打印出集合的元素个数
animals.add('cat')       
print(len(animals))
animals.remove('cat')     # 从集合里面移除某个元素

True
False
True
3
3


### 3.字典
字典里面存在的都是数据对，这些数据都是以(key, value)的形式存在，且存在映射关系

In [48]:
d = {'cat': 'cute', 'dog': 'furry'}  # 创造一个字典
print(d['cat'])       # 取得字典中的某个元素
print('cat'in d)     # 判断字典中key是否有该元素

cute
True


In [50]:
d['fish'] = 'wet'   # 字典中添加一个新元素
print(d)

{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}


In [55]:
print(d.get('monkey', 'None'))  # 如果元素在字典的key中，返回其对应的值，否则返回get中的值
print(d.get('fish', 'None'))

None
wet


In [57]:
del d['fish']         # 从字典中移除某个元素
print(d.get('fish', 'None')) # fish被移除之后，不能显示出'wet'

None


### 4.元组
一个元组和列表类似，但是元组是无法改变的。同时一个最大的不同是元组可以作为字典中的key，而列表不可以。

In [66]:
d = {(x, x+1): x for x in range(10)} # 使用元组创造一个字典
t = (5, 6)        # 创造一个元组
print(type(t))    # 打印出元组的类型
print(d[t])       # 打印出字典中对应于(5, 6)的元素
print(d[(1, 2)])  # 打印出字典中对应于(1, 2)的元素

<class 'tuple'>
5
1


# 函数
函数通过def来定义，将一些重复使用的操作封装在一起，每次不需要重复写相同的代码，只需要调用函数就可以了

In [67]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero' 
for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


# 类
类和实例是面向对象中重要的概念，必须牢记类是抽象的模板，而实例是根据类创建出来的一个个具体的“对象”，每个对象都拥有相同的方法，但各自的数据可能不同

In [73]:
class Student():
    def __init__(self, name, score):
        self.name = name
        self.score = score
    def print_score(self):
        print('name:',self.name,'score:',self.score)

stu = Student('小明',88)
stu.print_score()

name: 小明 score: 88


# Numpy
### 1.数组(Arrays)
数组就是一个任意维度的矩阵，数组的维度就是矩阵的秩，数组内部的数据类型和python的数据类型一致

In [78]:
import numpy as np

In [79]:
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a.dtype)

<class 'numpy.ndarray'>
(3,)
int32


### 2.数组索引
Numpy也支持多种类型的数据索引，比如切片，整数值索引和布尔值索引

In [83]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [84]:
b = a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [82]:
bool_idx = a>6
print(bool_idx)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


### 3.数学计算
numpy中支持很多线性代数的数学运算

In [91]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [92]:
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]


### 补充

In [93]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [94]:
print(np.sum(x))
print(np.sum(x, axis=0))

10
